spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://mysql:3306/foo?useSSL=false
    url: jdbc:mysql://localhost:3306/foo?useSSL=false
    username: root
    password: root

